[versions]
android-min-sdk = "24"
android-compile-sdk = "31"
android-target-sdk = "31"
compose-androidx = "1.3.0-beta02"
compose-compiler = "1.3.0"
compose-jetbrains = "1.2.0-alpha01-dev755"
coroutines = "1.6.4"
kmm-bridge = "0.3.2"
kotlin = "1.7.10"
kotlinx-serialization = "1.4.0"
store = "4.0.5"
okio = "3.2.0"
okHttp = "4.9.1"
viewmodel = "2.6.0-alpha02"
zipline = "0.9.4"

[libraries]
androidx-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "viewmodel"}

kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines"}

compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "compose-compiler" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-androidx" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose-androidx" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-androidx" }

store = {group = "com.dropbox.mobile.store", name="store4", version.ref = "store"}

okio-core = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
okHttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }

zipline-zipline = { group = "app.cash.zipline", name = "zipline", version.ref = "zipline" }
zipline-loader = { group = "app.cash.zipline", name = "zipline-loader", version.ref = "zipline" }